import { RecipeType } from '@/app/types/interface';
import { CookingPot, Wheat } from 'lucide-react';
// import Slider from '@/components/swiper/slider';
import { GetServerSidePropsContext, Metadata } from 'next';
import dynamic from 'next/dynamic';
import Image from 'next/image';
import { useParams } from 'next/navigation';
import React from 'react'
const Slider = dynamic(() => import('@/components/swiper/slider'), { ssr: false });

async function getRecipe(context: GetServerSidePropsContext) {
    'use server';
    try {
        const { recipeId } = context.params!;

        if (recipeId === undefined) return null;

        const response = await fetch(`http://localhost:3000/api/recipe/${recipeId}`, { method: 'GET' });
        const data = await response.json();

        if (!data.success) {
            throw new Error(data.message);
        }

        return data.data;
    } catch (error) {
        throw new Error(`Failed to fetch recipe: ${error}`);
    }
}

export const metadata: Metadata = {
    title: "Recipe Details",
    description: "Generated by create next app",
};


async function DetailsRecipe(context: GetServerSidePropsContext) {
    let recipe: RecipeType | null = null;
    let error: string | null = null;

    try {
        recipe = await getRecipe(context);
    } catch (e) {
        error = e instanceof Error ? e.message : String(e);
    }
    if (recipe) {
        console.log(recipe);
    }

    return (
        <>
            {recipe && (
                <div className='flex flex-col justify-center'>

                    <h1 className='text-5xl'>{recipe.title}</h1>

                    <section>
                        <Image
                            src={recipe.imageUrl}
                            height={300}
                            width={300}
                            alt={recipe.title}
                            className='rounded-md'
                        />
                        <p>{recipe.instructions}</p>
                    </section>

                    <section>
                        <Slider steps={recipe.steps} />
                    </section>

                    <section>
                        <span className='text-2xl flex flex-row items-center gap-3'>
                            <Wheat />
                            <h2>Ingredients</h2>
                        </span>
                        <div className='my-3 py-3 flex flex-row gap-5 p-3'>
                            {recipe.RecipeIngredients.map((recipeIngredient) => (
                                <div key={recipeIngredient.id} className='flex flex-col items-center'>
                                    <Image
                                        src={recipeIngredient.ingredient.imageUrl}
                                        height={100}
                                        width={100}
                                        alt={recipeIngredient.ingredient.name}
                                        className='size-[100px] rounded-md object-fill'
                                    />
                                    <p>
                                        {recipeIngredient.ingredient.name}
                                    </p>
                                    <p>{recipeIngredient.quantity} {recipeIngredient.unit}</p>
                                </div>
                            ))}
                        </div>
                    </section>

                    <section>
                        <span className='text-2xl flex flex-row items-center gap-3'>
                            <CookingPot />
                            <h2>Tools</h2>
                        </span>
                        <div className='my-3 py-3 flex flex-row gap-5 p-3'>
                            {recipe.RecipeTools.map((recipeTool) => (
                                <div key={recipeTool.id} className="flex flex-col items-center">
                                    <Image
                                        src={recipeTool.tool.imageUrl}
                                        height={100}
                                        width={100}
                                        alt={recipeTool.tool.name}
                                        className='size-[100px] rounded-md object-fill'
                                    />
                                    <p>{recipeTool.tool.name}</p>
                                </div>
                            ))}
                        </div>
                    </section>

                </div>
            )}
        </>
    )
}

export default DetailsRecipe