import { RecipeType } from '@/app/types/interface';
import { GetServerSidePropsContext, Metadata } from 'next';
import Image from 'next/image';
import { useParams } from 'next/navigation';
import React from 'react'

async function getRecipe(context: GetServerSidePropsContext) {
    'use server';
    try {
        const { recipeId } = context.params!;

        if (recipeId === undefined) return null;

        const response = await fetch(`http://localhost:3000/api/recipe/${recipeId}`, { method: 'GET' });
        const data = await response.json();

        if (!data.success) {
            throw new Error(data.message);
        }

        return data.data;
    } catch (error) {
        throw new Error(`Failed to fetch recipe: ${error}`);
    }
}

export const metadata: Metadata = {
    title: "Recipe Details",
    description: "Generated by create next app",
};


async function DetailsRecipe(context: GetServerSidePropsContext) {
    let recipe: RecipeType | null = null;
    let error: string | null = null;

    try {
        recipe = await getRecipe(context);
    } catch (e) {
        error = e instanceof Error ? e.message : String(e);
    }
    if (recipe) {
        console.log(recipe);
    }

    return (
        <div>
            {recipe && (
                <>
                    <Image
                        src={recipe.imageUrl}
                        height={300}
                        width={300}
                        alt={recipe.title}
                    />
                    <p>{recipe.title}</p>
                    <p>{recipe.instructions}</p>

                    <div className='flex flex-row flex-wrap gap-2'>
                        {recipe.steps.map((step, index) => (
                            <div key={index} className='border border-white flex-1'>
                                <p className='text-center'>{index + 1}. {step}</p>
                            </div>
                        ))}
                    </div>

                    <div className='border border-white my-3 py-3'>
                        <h2>Ingredients</h2>
                        {recipe.RecipeIngredients.map((recipeIngredient) => (
                            <div key={recipeIngredient.id} className='flex flex-row items-center'>
                                <Image
                                    src={recipeIngredient.ingredient.imageUrl}
                                    height={50}
                                    width={50}
                                    alt={recipeIngredient.ingredient.name}
                                />
                                <p>
                                    {recipeIngredient.ingredient.name} - {recipeIngredient.quantity} {recipeIngredient.unit}
                                </p>
                            </div>
                        ))}
                    </div>

                    <div className='border border-white my-3 py-3'>
                        <h2>Tools</h2>
                        {recipe.RecipeTools.map((recipeTool) => (
                            <div key={recipeTool.id} className="flex flex-row items-center">
                                <Image
                                    src={recipeTool.tool.imageUrl}
                                    height={50}
                                    width={50}
                                    alt={recipeTool.tool.name}
                                />
                                <p>1x {recipeTool.tool.name}</p>
                            </div>
                        ))}
                    </div>
                </>
            )}
        </div>
    )
}

export default DetailsRecipe